### ISSUE TITLE
Flyers Getting Started

### ISSUE THREAD

**Issue by timokoenig** [timokoenig/hostrefugees#13]
Let's create flyers (in business card size) with the website and important numbers on it

**Front**
hostrefugees.eu
[LOGO]

**Back**
Getting Started / Починаємо
hostrefugees.eu/getting-started
Police / Поліція: 110
Ambulance / Швидка допомога : 112

**Comment by timokoenig** [comment]
hostrefugees.eu/getting-started will lead the user to https://github.com/timokoenig/hostrefugees/issues/1

**Comment by JilAuraya** [comment]
I like this idea. Flyers can be photographed or handed over. 

Maybe also stickers to stick to traffic lights or signposts: 
hostrefugees.eu
[LOGO]
Police / Поліція: 110
Ambulance / Швидка допомога : 112

**Comment by timokoenig** [comment]
@JilAuraya Just pushed an initial version that I will send to someone who will further refine it

https://github.com/timokoenig/hostrefugees/blob/main/material/BusinessCard_HostRefugees.pdf

**Comment by timokoenig** [comment]
That's the first version we will go with 
https://github.com/timokoenig/hostrefugees/blob/main/public/docs/BusinessCard_HostRefugees.pdf
