### ISSUE TITLE
Feature: Hosting refugees' pets

### ISSUE THREAD

**Issue by JilAuraya** [timokoenig/hostrefugees#21]
Situation: 
Many refugees have pets at home and either leave them in the Ukraine or bring them along on their dangerous journey. For those who bring them along the borders can be a difficult situation. 

What happens at the border exactly? 

What happens or has to be done to the pets arriving in Germany? 

Idea: 
As an additional feature, people can search for a place for their pets or people "apply" to take care of animals. Some people may cannot host people, but they can take care of animals and I believe that many refugees would be more than grateful if they knew their pet is taken good care of. 

Information: 

Rules in Germany: 
- Vaccination and 21-day quarantine of the animals is mandatory
- You will receive a microchip, an animal ID card and a rabies vaccination 
- Volunteers need at least a two-room apartment to keep the dog or cat away from people and other animals. If an animal is taken in, helpers must also notify the local veterinary office using a form. Medical officers can then check whether the quarantine conditions are really met 

_to be continued_

**Comment by timokoenig** [comment]
@JilAuraya does this mean that a pet can also quarantine with a private host and not only in a shelter?

**Comment by timokoenig** [comment]
Do we want to give the host also the opportunity to apply for pets instead of guests applying for pet hosts?

**Comment by timokoenig** [comment]
Can we create a prefilled form that the person shows at the border to verify a private quarantine place? What are the legal requirements?

**Comment by JilAuraya** [comment]
I suggest we handle this topic in two waves. 

**1. Wave:** Hosts can add places only for pets, refugees can apply for their pets there
= small adjustments
- Requirements 
-> animal ID card
-> rabies vaccination (approx. 20-30€)
-> 21 day quarantine 
-> dogs need to be chipped (40-60€)
-> hosts need to live in a > 2 room apartment (in case of rabies the pet needs to isolated) 
-> If an animal is taken in, helpers must also use a form to notify the local veterinary office (they will also check the quarantine conditions)
- What else
-> information on how to take care of pets (especially cats and dogs) 
-> exchange and visits with pet's owners 

**2. Wave:** Hosts can apply to take care of refugee's pets 
= big adjustments
- Refugees can upload pictures and information regarding their pet. People who can host pets but no guests can apply to take those pets in. 
- requirements same as in wave 1 
- Information needed about the pet: 
-> name, age, picture(s) 
-> vaccinated? if yes, against what? 
-> insured? if yes, where? 
-> for dogs: chipped? 
-> information regarding behaviour 
-> "do's and dont's" 
-> additional important information, such as illness, intolerances, preferences, etc. 
-> documents available? (vaccination card, insurance, etc.)

**Comment by JilAuraya** [comment]
First wave is live.

**Comment by timokoenig** [comment]
Will move the "second wave" to a new ticket because we will handle this together with the people guest listings

ref: https://github.com/timokoenig/hostrefugees/issues/43
