### ISSUE TITLE
Feature: women hosting women

### ISSUE THREAD

**Issue by BeaCza** [timokoenig/hostrefugees#32]
A friend of mine recently said that she would like to host a refugee but that she'd only feel comfortable taking in women. Right now, as a host she could decline a male refugee, right? But we could make this process more smooth by including a feature for this?

**Comment by timokoenig** [comment]
You're right, currently only the guest can see if the residents at the place are all female or not. The host does not see who is coming to the place, except the number of adults and children. We could add an option for the host to show this requirement on the place detail page.

This would also reduce the amount of declined requests

**Comment by timokoenig** [comment]
Added an extra field to indicate whether only women are allowed to stay at that place.
