### ISSUE TITLE
Waiting List for Guests

### ISSUE THREAD

**Issue by timokoenig** [timokoenig/hostrefugees#34]
Accommodations are still rare and to improve the user experience from not finding anything new we will add a guest waiting list.

A guest can register on the platform and enable the waiting list feature.
Then we will send out an email with new accommodations once a day to those users.

In the future we could improve this feature by adding filter conditions so that we show only relevant accommodations to that guest.

**Comment by JilAuraya** [comment]
Specifications: 

On https://hostrefugees.eu: 
Two ideas: 
1) Right below "Available Places" / "Welcome to Germany" (Button text: Put yourself on our waiting list) 
2) Below "See more Places" (Button text: or join our waiting list now)
3) Both

On https://hostrefugees.eu/place: 
Below Available Places we show a button "Didn't find a suitable accommodation?" 
After clicking the button the person will be directed to a form with the header: **Waiting List** 
Below an information text: **Hosts can join at any time. We inform you when there are new available accommodations.** 
The form includes following information: 
Name: 
Email: 
Button: Send 

Ideas for further expansion: 
- setting parameters like city 
- only informing if available beds and guests match 
- only informing when pets welcome match

**Comment by timokoenig** [comment]
Added the waiting list on both pages. Done for now.
