### ISSUE TITLE
Stay Request - Decline Message

### ISSUE THREAD

**Issue by JilAuraya** [timokoenig/hostrefugees#36]
It would be a nice gesture and feature to be able to send a decline message. 
Currently the host can either accept or decline the request. 
Either way, but imo more importantly for declining, it would be nice for the host to send a little message with the decline. Maybe stating the reason or any other kind of message. 

This would be in the feature group of chat functionality.

**Comment by timokoenig** [comment]
I think that is a great feature for the in-app chat / bot functionality

ref https://github.com/timokoenig/hostrefugees/issues/7

**Comment by timokoenig** [comment]
Done.
