### ISSUE TITLE
The site is down

### ISSUE THREAD

**Issue by Ein-Tim** [timokoenig/hostrefugees#48]
Is it expected that the website is down?

**Comment by Ein-Tim** [comment]
Fyi @timokoenig

**Comment by timokoenig** [comment]
@Ein-Tim sorry for the late reply. This is known and the site will be back up online beginning next week. Thanks you for the hint!

**Comment by Ein-Tim** [comment]
Still down...

**Comment by Ein-Tim** [comment]
Still down, see also ![Website](https://img.shields.io/website?down_message=offline&label=webapp&up_message=online&url=https%3A%2F%2Fhostrefugees.eu)

**Comment by timokoenig** [comment]
The site is back up but the service not available at the moment. I will post updates as soon as I can.
