### ISSUE TITLE
Safety Check

### ISSUE THREAD

**Issue by timokoenig** [timokoenig/hostrefugees#5]
We want to ensure that refugees arrive safe at their temporary home, so we need a safety check for the Guest and Host.

**Current Idea:**
When the guest arrives at the hosts place, both parties confirm the safety check on the website. If the safety check is not confirmed within 24 hours, we will get in touch with both parties.

**Future Ideas:**
* Add additional safety checks after x days / weeks?
* Additional questions to check the correctness of the place offering

**Comment by Ein-Tim** [comment]
What definitely should also be ensured is that the place where the refugees will stay is in an acceptable condition. 

Rest sounds very good, an additional safety check could be implemented after 1, 3 & 7 days (if you don't think that's too much).

**Comment by timokoenig** [comment]
True, this can be done with additional questions for the guests after they arrive at the place. In general each place has photos already indicating how the place should look like.

Additional safety checks are important but too many could also cause an increase in work for us. Some might forget the check and then we would need to call one after another.

**Comment by JilAuraya** [comment]
I would currently suggest two safety checks: 
1. within 48h to make sure the people are well and arrived at their place of destination
2. within one to two weeks to ensure everything stayed in good condition and the hosts / guests behave good.

**Comment by timokoenig** [comment]
For now I only implemented the first safety check

<img width="637" alt="Screen Shot 2022-03-25 at 10 44 28" src="https://user-images.githubusercontent.com/4365095/160101066-cba34094-dfc0-4f7a-81d5-58f5f6112d55.png">

<img width="635" alt="Screen Shot 2022-03-25 at 11 09 33" src="https://user-images.githubusercontent.com/4365095/160101078-c0ddaf9b-0498-45b5-9d06-22309501ee41.png">
