### ISSUE TITLE
Activities Around You

### ISSUE THREAD

**Issue by timokoenig** [timokoenig/hostrefugees#6]
Let's offer a feature to show activities, places, and other things around you based on the guests place location or a manual search (for everyone that is not being hosted)

**Activities can be**
* free sports offerings from sport clubs
* donation centers that give out clothes, food, and other essentials
* ...

**Comment by Ein-Tim** [comment]
Should the host enter these details while registering their place?

**Comment by timokoenig** [comment]
Yes, that could also be added and helps us to add content to the platform.

I know a lot of companies and clubs that would add activities as well

**Comment by timokoenig** [comment]
Added a simple bulletin board that should meet the current need. Later on we will improve this feature much more.

<img width="1290" alt="Screen Shot 2022-03-28 at 00 42 40" src="https://user-images.githubusercontent.com/4365095/160304290-e12df157-0429-4de3-a2b9-159de2cec84f.png">

<img width="1359" alt="Screen Shot 2022-03-28 at 00 45 30" src="https://user-images.githubusercontent.com/4365095/160304320-cd7cae82-866b-4004-9eb1-db20bc5b29bc.png">
