### ISSUE TITLE
Improve communication process after guest gets accepted

### ISSUE THREAD

**Issue by timokoenig** [timokoenig/hostrefugees#7]
**Current Implementation:**
After a host accepts a guest to their place, both receive an email with the following information:

* Full Name
* Address
* Email / Phone number
* Hosts and Guests languages
* An info text to contact each other and to arrange the arrival

**Improvement Ideas**
* The email should be available in English and the first language of the guest
* The host can enter arrival instructions for each place
* Should we offer an InApp chat functionality? (Emails are so old school)

**Comment by JilAuraya** [comment]
I think a chat functionality between host and guests would be amazing to exchange quickly. 
In addition I think having a video chat before the entire address is provided would also be a nice to have :)

**Comment by timokoenig** [comment]
Done; implemented a chat with automatic translation of all messages
